### ISSUE TITLE
Script Will Not Set Wallpaper on Pop!_OS

### ISSUE THREAD

**Issue by AlexanderDavid** [NuLL3rr0r/reddit-wallpaper#1]
I am using the latest Pop!_OS 19.04 and the script doesn't set the wallpaper. There are no errors in the log that is printed out and it successfully downloads the pictures into the `.cache/reddit_wallpapers/` location.

**Comment by AlexanderDavid** [comment]
It turns out the reason for this is that GNOME doesn't accept the way that Feh sets the wallpaper. I have made a pull request  #2  for some changes that I did to set the wallpaper using gsettings if the user is using gnome.

**Comment by NuLL3rr0r** [comment]
Your pull request #2 is merged. Thank you.
